name: "Install Tippecanoe"
description: "Install Tippecanoe from source (GitHub repository)"
# inputs:
# outputs:
runs:
  using: "composite"
  steps:
    - run: git clone https://github.com/mapbox/tippecanoe.git
      shell: bash
    - run: |
        cd tippecanoe
        make -j
        sudo make install
      shell: bash
