name: 🇧🇪 Belgium

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:

  openstreetmap-buffers:
    name: Generate OpenStreetMap buffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PROJ
        run: |
          sudo apt install libcurl4-gnutls-dev
          wget https://download.osgeo.org/proj/proj-7.1.1.tar.gz
          tar -xf proj-7.1.1.tar.gz
          cd proj-7.1.1
          ./configure
          make
          sudo make install
      - name: Install GDAL
        run: |
          wget https://github.com/OSGeo/gdal/releases/download/v3.1.3/gdal-3.1.3.tar.gz
          tar -xf gdal-3.1.3.tar.gz
          cd gdal-3.1.3
          ./configure
          make
          sudo make install
      - name: Install Tippecanoe
        run: |
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install
      - name: Run process
        run: sh data/belgium/openstreetmap.sh
      - name: Upload OpenStreetMap buffers
        uses: actions/upload-artifact@v2
        with:
          name: OpenStreetMap-Belgium-Buffers
          path: data/belgium/belgium-buffers.mbtiles

  flanders-diff:
    name: Generate difference for Flanders
    needs: openstreetmap-buffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PROJ
        run: |
          wget https://download.osgeo.org/proj/proj-7.1.1.tar.gz
          tar -xf proj-7.1.1.tar.gz
          cd proj-7.1.1
          ./configure
          make
          sudo make install
      - name: Install GDAL
        run: |
          wget https://github.com/OSGeo/gdal/releases/download/v3.1.3/gdal-3.1.3.tar.gz
          tar -xf gdal-3.1.3.tar.gz
          cd gdal-3.1.3
          ./configure
          make
          sudo make install
      - name: Install Tippecanoe
        run: |
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install
      - name: Download OpenStreetMap buffers
        uses: actions/download-artifact@v2
        with:
          name: OpenStreetMap-Belgium-Buffers
          path: data/belgium/belgium-buffers.mbtiles
      - name: Run process
        run: sh data/belgium/flanders/process.sh
      - name: Upload difference
        uses: actions/upload-artifact@v2
        with:
          name: Flanders-Difference
          path: data/belgium/flanders/process/notWithin.geojson
      - name: Upload statistics
        uses: actions/upload-artifact@v2
        with:
          name: Flanders-Statistics
          path: data/belgium/flanders/process/stats.json
