name: 🇧🇪 Belgium

on:
  push:
    paths:
      - ".github/workflows/belgium.yml"
      - "script/**/*.ts"
      - "data/belgium"
      - "!data/belgium/**/diff.geojson"
      - "!data/belgium/**/stats.json"
  pull_request:
    paths:
      - ".github/workflows/belgium.yml"
      - "script/**/*.ts"
      - "data/belgium"
      - "!data/belgium/**/diff.geojson"
      - "!data/belgium/**/stats.json"
  # schedule:
  #   - cron: '0 0 * * *'

jobs:

  openstreetmap-buffers:
    name: Generate OpenStreetMap buffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL
        run: sudo apt install gdal-bin
      - name: Install Tippecanoe
        run: |
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Download Belgium extract
        run: wget https://download.geofabrik.de/europe/belgium-latest.osm.pbf
      - name: Convert to GeoJSON
        run: |
          ogr2ogr -f "GeoJSON" -progress \
            -select "name,highway" \
            -where "highway is not null" \
            "belgium.geojson" \
            "belgium-latest.osm.pbf" "lines"
      - name: Generate buffers
        run: node "script/buffer.js" "belgium.geojson" "belgium-buffers.geojson"
      - name: Generate vector tiles
        run: |
          tippecanoe --force --no-feature-limit --no-tile-size-limit \
            --maximum-zoom=14 --minimum-zoom=14 \
            --layer="buffers" \
            --output="belgium-buffers.mbtiles" "belgium-buffers.geojson"
      # See https://github.com/actions/upload-artifact/issues/38
      - name: Compress vector tiles
        run: tar -czvf belgium-buffers.tar.gz belgium-buffers.mbtiles
      - name: Upload OpenStreetMap buffers
        uses: actions/upload-artifact@v2
        with:
          name: OpenStreetMap-Belgium-Buffers
          path: belgium-buffers.tar.gz

  flanders-diff:
    name: Generate difference for Flanders
    needs: openstreetmap-buffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL
        run: sudo apt install gdal-bin
      - name: Install Tippecanoe
        run: |
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Download & Unzip data
        run: |
          wget "https://downloadagiv.blob.core.windows.net/wegenregister/Wegenregister_SHAPE_20200917.zip"
          unzip "Wegenregister_SHAPE_20200917.zip"
      - name: Convert to GeoJSON
        run: |
          ogr2ogr -f "GeoJSON" -progress \
            --config SHAPE_ENCODING "ISO-8859-1" \
            -s_srs "EPSG:31370" -t_srs "EPSG:4326" \
            -sql "@data/belgium/flanders/filter.sql" \
            -lco COORDINATE_PRECISION=6 \
            "Wegsegment.geojson" \
            "Shapefile/Wegsegment.shp"
      - name: Convert fields to OpenStreetMap tags
        run: node "script/convert-tags.js" -c "data/belgium/flanders/convert.json" "Wegsegment.geojson" "WegsegmentTagged.geojson"
      - name: Generate vector tiles
        run: |
          tippecanoe --force --no-feature-limit --no-tile-size-limit \
            --buffer=0 \
            --maximum-zoom=14 --minimum-zoom=14 \
            --layer="roads" \
            --output="WegsegmentTagged.mbtiles" "WegsegmentTagged.geojson"
      - name: Compress vector tiles
        run: tar -czvf WegsegmentTagged.tar.gz WegsegmentTagged.mbtiles
      - name: Upload vector tiles
        uses: actions/upload-artifact@v2
        with:
          name: Wegenregister
          path: WegsegmentTagged.tar.gz
      - name: Download OpenStreetMap buffers
        uses: actions/download-artifact@v2
        with:
          name: OpenStreetMap-Belgium-Buffers
      # See https://github.com/actions/upload-artifact/issues/38
      - name: Extract
        run: tar -xzvf belgium-buffers.tar.gz
      - name: Difference
        run: node "script/difference.js" --output-dir="data/belgium/flanders/difference/Wegenregister_SHAPE_20200917" "WegsegmentTagged.mbtiles" "belgium-buffers.mbtiles"
      - name: Upload difference
        uses: actions/upload-artifact@v2
        with:
          name: Flanders-Difference
          path: data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/diff.geojson
      - name: Upload statistics
        uses: actions/upload-artifact@v2
        with:
          name: Flanders-Statistics
          path: data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/stats.json
      - name: Push to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/diff.geojson
          git add data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/stats.json
          git commit -m "🗃 Update difference for Flanders, Belgium"
          git push