name: Build and Deploy app

on:
  push:
    path:
      - "app/**"
      - "data/**/stats.json"
  pull_request:
    paths:
      - "app/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run export:githubio
        working-directory: app

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: app/__sapper__/export/road-completion # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
