name: Build and Deploy app

on:
  push:
    paths:
      - ".github/workflows/deploy-app.yml"
      - "app/**"
      - "data/**/diff.geojson"
      - "data/**/stats.json"
  pull_request:
    paths:
      - "app/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: app
    - run: npm run lint
      working-directory: app

  build-and-deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run export:githubio
        working-directory: app
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: app/__sapper__/export/road-completion # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
